apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_app
  namespace: dev
  labels:
    app: my_app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: my_app

  template:
    metadata:
      labels:
        app: my_app

    spec:
      containers:
        - name: my_app
          image: docker.io/thanuja/my_app:latest
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8085
