apiVersion: v1
kind: Service
metadata:
  name: my_app
  namespace: dev

spec:
  type: LoadBalancer

  selector:
    app: my_app

  ports:
    - name: http
      port: 80
      targetPort: 8085
      protocol: TCP
